image: node:12.13.1

pipelines:
  default:
    - step:
        name: Test
        caches:
          - node
        script:
          - npm install
          - npm test
          - npm run build
        artifacts:
          - dist/**
  branches:
    develop:
      - step:
          name: Test
#          caches:
#            - node
          script:
            - npm --version
            - npm cache clean --force
            - npm config set unsafe-perm true && npm install
            - ls node_modules/podger-money
            - npm test
            - npm run build
          artifacts:
            - dist/**
      - step:
          # set GCLOUD_PROJECT environment variable to your project ID
          # set GCLOUD_API_KEYFILE environment variable to base64-encoded keyfile as described here: https://confluence.atlassian.com/x/dm2xNQ
          name: Deploy to GCloud
          deployment: test   # set to test, staging or production
          image: google/cloud-sdk:latest
          script:
            - echo $GCLOUD_API_KEYFILE | base64 --decode --ignore-garbage > ./gcloud-api-key.json
            - gcloud auth activate-service-account --key-file gcloud-api-key.json
            - gcloud config set project $GCLOUD_PROJECT
            - >
              gcloud functions deploy depreciations
              --quiet
              --region europe-west1
              --runtime nodejs10
              --trigger-http
              --memory 256MB
              --entry-point main
