on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: podger-depreciations
      FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
      ARTIFACTS_BUCKET_NAME: ${{ secrets.ARTIFACTS_BUCKET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Run Unit Tests
        run: npm test
        env:
          CI: true
          SALARY_PARAMETERS_BUCKET: test

      - name: Build
        run: npm run build --if-present

      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCLOUD_API_KEYFILE }}
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          export_default_credentials: true

      - name: Run Integration Tests
        run: npm run test:integration --if-present
        env:
          CI: true

      - run: export VERSION=$(echo ${GITHUB_SHA} | cut -c1-7)

      - name: Package
        run: >
          zip ${ARTIFACT_NAME}-${VERSION}.zip
          package.json
          package-lock.json
          src/*.js

      - name: Push to GCS
        run: >
          gsutil cp
          ${ARTIFACT_NAME}-${VERSION}.zip
          gs://${ARTIFACTS_BUCKET_NAME}/${ARTIFACT_NAME}/${ARTIFACT_NAME}-${VERSION}.zip

      - name: Copy as latest
        run: >
          gsutil cp
          gs://${ARTIFACTS_BUCKET_NAME}/${ARTIFACT_NAME}/${ARTIFACT_NAME}-${VERSION}.zip
          gs://${ARTIFACTS_BUCKET_NAME}/${ARTIFACT_NAME}/${ARTIFACT_NAME}-latest.zip

      - name: Deploy
        run: >
          gcloud functions deploy ${FUNCTION_NAME}
          --quiet
          --region europe-west1
          --runtime nodejs10
          --trigger-http
          --memory 256MB
          --source gs://${ARTIFACTS_BUCKET_NAME}/${ARTIFACT_NAME}/${ARTIFACT_NAME}-latest.zip
          --entry-point main
